### ISSUE TITLE
Auditing your code

### ISSUE THREAD

**Issue by ayumi-cloud** [unitprotocol/core#1]
Hello,

In a twitter post you guys said the following:

![image](https://user-images.githubusercontent.com/57409060/90232817-1a96ee80-de15-11ea-814b-c010592b3162.png)

What third-party audit company are using, to check your code?

If you need to find one, maybe you could use the same one as the SBREE project is using, see their medium post: [BREE Smart Contract Audit Guideline](https://medium.com/@coinbreeder/bree-smart-contract-audit-guideline-109d60282a23)

They are using the auditing company: [Somish Blockchain Labs](https://www.somish.com/)

The reason I'm writing this issue is because I don't want to see this project do the same mistake YAM.Finance did yesterday and lose $500 million in liquidity due to a simple coding error in their project, see here: [Defi Project Yam Finance Sees Over $500M Locked in 24 Hours, Devs Reveal Contract Bug](https://news.bitcoin.com/new-defi-yield-farming-project-yam-finance-sees-460-million-locked-in-17-hours/)

Thanks and good luck.

**Comment by gleb-ch** [comment]
Hello. Thank you for your recommendation. We are working with audit companies that have a solid reputation and experience.
